# Generated by Django 4.0.5 on 2022-11-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_url', models.URLField(blank=True)),
                ('unit_price', models.FloatField()),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
