# Generated by Django 4.0.5 on 2022-11-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'billing_location',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('deliver_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_status', models.CharField(choices=[('failed', 'Rejected'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('success', 'Accepted')], default='pending', max_length=20)),
                ('request_id', models.CharField(default='', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.customer')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
