# Generated by Django 4.0.5 on 2022-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('success', 'Accepted'), ('delivered', 'Delivered'), ('failed', 'Rejected')], default='pending', max_length=20),
        ),
    ]
