# Generated by Django 4.0.5 on 2022-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_alter_cart_item_alter_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Accepted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Rejected')], default='pending', max_length=20),
        ),
    ]
