# Generated by Django 4.0.5 on 2022-11-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_customer_first_name_remove_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='phone',
        ),
    ]
